server:
  port: 8080
  timezone: ${SERVER_TIMEZONE:IST}
  servlet:
    context-path: /core

spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/mynextduty_db
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  hikari:
    pool-name: CoreHikariPool
    maximum-pool-size: 15
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000

# Logging
logging:
  level:
    com.mynextduty: DEBUG
    org.springframework.security: DEBUG

core:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION:259200000} # 3 days in milliseconds




